### ISSUE TITLE
[Fabric] - Startup error

### ISSUE THREAD

**Issue by kanagawawave** [MiniPlaceholders/Expressions-Expansion#66]
-Installed mods:

Expressions-Expansion-Fabric-v1.1.1
MiniPlaceholders-LuckPerms-Expansion-Fabric-1.4.1
MiniPlaceholders-Fabric-2.2.3
LuckPerms-Fabric-5.4.108
fabric-api-0.90.0+1.20.2

-Logs:
```[09:36:42] [main/INFO]: Fix: add [], remove [], replace [[expressionsexpansion 1.1.1] -> add:expressionsexpansion 1 ([(-?,?)])]
[09:36:42] [main/ERROR]: Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
         - Replace mod 'Expressions-Expansion' (expressionsexpansion) 1.1.1 with any version that is compatible with:
                 - minecraft 1.20.2
More details:
         - Mod 'Expressions-Expansion' (expressionsexpansion) 1.1.1 requires any version between 1.19.4 (inclusive) and 1.20- (exclusive) of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.2!
        at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51) ~[fabric-loader-0.14.23.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:194) ~[fabric-loader-0.14.23.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146) ~[fabric-loader-0.14.23.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) ~[fabric-loader-0.14.23.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.14.23.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.14.23.jar:?]

**Comment by 4drian3d** [comment]
Fixed in the new version

**Comment by kanagawawave** [comment]
> Fixed in the new version

Checked, no errors but mod isnt loading on startup.
Opened with 7z and seems to not contain any fabric files inside, only paper and velocity

**Comment by 4drian3d** [comment]
> > Fixed in the new version
> 
> Checked, no errors but mod isnt loading on startup. Opened with 7z and seems to not contain any fabric files inside, only paper and velocity

There are 2 versions, one that works with Paper, Velocity and Sponge and one that works with Fabric, make sure you have downloaded the one with Fabric in the name
